data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifiers.klaudiusz]
name = "klaudiusz"
public_key = "91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
[[chains]]
name = "joystream-node"
title = "Joystream"
color = "#4038FF"
icon = "https://github.com/Joystream/design/blob/master/logo/joystream/logo%20icon/PNG/Icon-mono-white-1bg-blue-5x.png?raw=true"
rpc_endpoints = [
    "wss://rpc.joystream.org:9944/ws-rpc",
    "wss://monitoring.joyutils.org/ws-rpc",
]
testnet = false
verifier = "klaudiusz"
